{{- $fullName := include "kibana.fullname" . }}
{{- $labels : = include "kibana.labels" . }}
{{- with .Values.serversTransport }}
{{- if .enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: {{ $fullName }}
  labels:
    {{ toYaml $labels | nindent 4 }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
{{- end }}
