{{- $fullName := include "fleet-server.fullname" . }}
{{- $fleetLabels := include "fleet-server.labels" . }}
{{- range $index, $Agent := .Values.agents }}
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: {{ $Agent.name }}-{{ $fullName }}
  labels:
    {{- toYaml $fleetLabels | nindent 4 }}
    {{- if $Agent.labels }}
    {{- toYaml $Agent.labels | ninednt 4 }}
    {{- end }}
  annotations:
    eck.k8s.elastic.co/license: basic
    {{- if $Agent.annotations }}
    {{- toYaml $Agent.annotations | nindent 4 }}
    {{- end }}
spec:
  version: {{ required "A Fleet Server version is required" $Agent.version }}
  mode: fleet
  {{- toYaml $Agent.spec | nindent 2 }}
{{- end }}
